# Generated by Django 2.2 on 2019-04-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_name', models.CharField(max_length=50)),
                ('key_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graph.Graph_Key')),
            ],
        ),
    ]
