# Generated by Django 2.2 on 2019-04-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graph', '0002_graph_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_name',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
