# Generated by Django 2.2 on 2019-04-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graph', '0003_graph_name_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph_name',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
