# Generated by Django 2.2 on 2019-04-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graph', '0004_auto_20190420_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvimport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y-%m-%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='graph_axis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphName', models.CharField(max_length=200)),
                ('x_axis', models.CharField(max_length=200)),
                ('hue', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GraphType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_name', models.CharField(max_length=120)),
            ],
        ),
    ]
